public class seventh{
    public static void main (String args[]){
        System.out.print("Learn");
        System.out.print("\t");
        System.out.println("Java");
        System.out.print("\t\t");
        System.out.println("the");
        System.out.print("Hard");
        System.out.print("\t");
        System.out.println("way");
        System.out.println();
        System.out.print("\t\t");
        System.out.print("Learn Java the");
        System.out.print("\s");
        System.out.print("\"");
        System.out.print("Hard");
        System.out.print("\"");
        System.out.print("\s");
        System.out.println("Way!");
        System.out.println("Hello");
        System.out.println("Jelly");
        System.out.println("Hard to believe, eh?");
        System.out.print("Suprised?");
        System.out.print("\s");
        System.out.print("/*");
        System.out.print("\s");
        System.out.print("abcde");
        System.out.print("\s");
        System.out.print("*/");
        System.out.print("\s");
        System.out.println("Or what did you expect?");
        System.out.print("\\");
        System.out.print("\s");
        System.out.print("//");
        System.out.print("\s");
        System.out.print("-==-");
        System.out.print("\s");;
        System.out.print("\\");
        System.out.print("\s");
        System.out.println("//");
        System.out.print("\\");
        System.out.print("\\");
        System.out.print("\s");
        System.out.print("\\");
        System.out.print("\\");
        System.out.print("\\");
        System.out.print("\s");
        System.out.print("\\");
        System.out.print("\\");
        System.out.print("\\");
        System.out.println("\\");
        System.out.print("I hope you understand");
        System.out.print("\s");
        System.out.print("\"");
        System.out.print("escape sequences");
        System.out.print("\"");
        System.out.print("\s");
        System.out.print("now.");
    }
}